exec-once = awww-daemon
exec-once = hypridle
exec-once = swayosd-server
exec-once = playerctld
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = systemctl --user enable --now easyeffects
exec-once = ~/.config/hypr/scripts/volume_listener.sh
exec-once = quickshell -p ~/.config/hypr/scripts/quickshell/Main.qml
exec-once = quickshell -p ~/.config/hypr/scripts/quickshell/TopBar.qml
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = sleep 3 && hyprctl dispatch movewindowpixel "exact -5000 -5000,title:^(qs-master)$" && hyprctl dispatch resizewindowpixel "exact 1 1,title:^(qs-master)$"
