# ───────── Source all configs ─────────
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/window-rules.conf
source = ~/.config/hypr/autostart.conf
# source = ~/.config/hypr/hypridle.conf

# ───────── General ─────────
general {
    border_size = 0
    gaps_in = 4
    gaps_out = 4
    resize_on_border = true
    extend_border_grab_area = 30
}

# ───────── Decoration ─────────
decoration {
    rounding = 4
    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

# ───────── Input ─────────
input {
    kb_layout = us, ru
    kb_variant =
    kb_model =
    kb_rules =

    touchpad {
        natural_scroll = true
    }

    accel_profile = flat
}

# ───────── Misc ─────────
misc {
    font_family = JetBrains Mono
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = true
}

# ───────── Env vars ─────────
env = NIXOS_OZONE_WL,1
