# ───────── Source all configs ─────────
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/window-rules.conf
source = ~/.config/hypr/autostart.conf
# source = ~/.config/hypr/hypridle.conf

# ───────── General ─────────
general {
    border_size = 0 
    col.active_border = 0x00000000
    col.inactive_border = 0x00000000
    gaps_in = 4
    gaps_out = 4
    resize_on_border = true
    extend_border_grab_area = 30
}

# ───────── Decoration ─────────
decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 1.0

   blur {
        enabled = true
        size = 3 
        passes = 3
        noise = 0.0117
        contrast = 0.8916
        brightness = 0.8172
        vibrancy = 0.1696
        vibrancy_darkness = 0.0
        new_optimizations = true
        xray = false
        popups = true
    }

    shadow {
        enabled = true
    }
}

# ───────── Input ─────────
input {
    kb_layout = us, ru
    kb_variant =
    kb_model =
    kb_rules =

    touchpad {
        natural_scroll = true
    }

    accel_profile = flat
}

# ───────── Cursor ─────────
cursor {
    no_warps = true
    no_break_fs_vrr = false
    enable_hyprcursor = true
    # Disable the hover border highlight that appears on GUI apps
    hotspot_padding = 1
    inactive_timeout = 0
}

# ───────── Misc ─────────
misc {
    font_family = JetBrains Mono
    disable_hyprland_logo = true
    disable_splash_rendering = true
    focus_on_activate = false
}

# ───────── layout ─────────
dwindle {
    pseudotile = true
    preserve_split = true
    smart_resizing = true
}

# ───────── Env vars ─────────
env = NIXOS_OZONE_WL,1
