general {
    lock-cmd = hyprlock --config ~/.config/hypr/hyprlock/hyprlock.conf                     # Use hyphen -
    before-sleep-cmd = loginctl lock-session # Use hyphen -
}

listener {
    timeout = 600
    on-timeout = systemctl suspend           # Use hyphen -
}
