
# ─────────────────────────────
# Layer rules
# ─────────────────────────────
layerrule = no_anim on, match:namespace ^(volume_osd)$
layerrule = no_anim on, match:namespace ^(brightness_osd)$
layerrule = no_anim on, match:namespace ^(usb_popup)$
layerrule = no_anim on, match:namespace hyprpicker

# ─────────────────────────────
# Window rules
# ─────────────────────────────

windowrule {
    name = music-visualizer
    match:class = ^(music_vis)$
    float = on
    pin = on
    no_initial_focus = on
    size = 700 350
    move = 12 720
    border_size = 0
    no_shadow = on
}

windowrule {
    name = counter-strike
    match:class = ^(cs2)$
    immediate = on
    keep_aspect_ratio = on
}

windowrule {
    name = launcher
    match:title = ^(app-launcher)$
    float = on
    center = on
    size = 1200 600
    animation = slide
}

windowrule {
    name = quickshell-master
    match:title = ^(qs-master)$
    float = on
    pin = on 
    no_initial_focus = on 
}


# Nautilus  –  xray so blur samples the wallpaper directly
windowrule {
    name      = nautilus-blur
    match:class = ^(org\.gnome\.Nautilus)$
    xray      = off
    opacity   = 0.95 0.95
}
 
# Spotify  –  glassy dark look, blur composited layers
windowrule {
    name      = spotify-blur
    match:class = ^(spotify)$
    xray      = on
    opacity   = 0.90 0.87
    no_dim    = on
}

# Firefox  –  disable blur (performance + text clarity)
windowrule {
    name      = zen-blur
    match:class = ^(zen)$
    no_blur   = off
    opacity   = 0.97 0.97
}


