# ─────────────────────────────
# Layer rules (OSD / overlays)
# ─────────────────────────────
layerrule = noanim, ^(volume_osd)$
layerrule = noanim, ^(brightness_osd)$
layerrule = noanim, ^(usb_popup)$
layerrule = noanim, hyprpicker

# ─────────────────────────────
# Window rules
# ─────────────────────────────

# ───────── music_vis ─────────
windowrulev2 = float, class:^(music_vis)$
windowrulev2 = pin, class:^(music_vis)$
windowrulev2 = noinitialfocus, class:^(music_vis)$
windowrulev2 = size 700 350, class:^(music_vis)$
windowrulev2 = move 12 720, class:^(music_vis)$
windowrulev2 = noborder, class:^(music_vis)$
windowrulev2 = noshadow, class:^(music_vis)$

# ───────── CS2 ─────────
windowrulev2 = immediate, class:^(cs2)$
windowrulev2 = keepaspectratio, class:^(cs2)$

# ───────── App Launcher ─────────
windowrulev2 = float, title:^(app-launcher)$
windowrulev2 = center, title:^(app-launcher)$
windowrulev2 = size 1200 600, title:^(app-launcher)$
windowrulev2 = animation slide, title:^(app-launcher)$

# ───────── MASTER QUICKSHELL CONTAINER ─────────
windowrulev2 = float, title:^(qs-master)$
windowrulev2 = pin, title:^(qs-master)$
windowrulev2 = noshadow, title:^(qs-master)$
windowrulev2 = noborder, title:^(qs-master)$
windowrulev2 = move -5000 -5000, title:^(qs-master)$
windowrulev2 = noinitialfocus, title:^(qs-master)$
