# General
window_padding_width 12
background_opacity 0.75
background #1e1e2e

# Cursor
cursor_shape beam
cursor_blink_interval 0.5 

# No title bar decorations
hide_window_decorations yes

# Tab bar
tab_bar_style powerline

# Fonts
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.0
